/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gsak3
 */
public class StockFrame extends javax.swing.JFrame {

    /**
     * Creates new form StockFrame
     */
    public StockFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imerominiaGen = new javax.swing.JTextField();
        dieuthinsi = new javax.swing.JTextField();
        onoma = new javax.swing.JTextField();
        eponymo = new javax.swing.JTextField();
        arithmosPaidiwn = new javax.swing.JTextField();
        titlosPtyxiou = new javax.swing.JTextField();
        titlosMetaptixiakou = new javax.swing.JTextField();
        xronosProypiresias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vathmosPtyxiou = new javax.swing.JTextField();
        imerominiaPtyxiou = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        imerominiaMetaptyxiakou = new javax.swing.JTextField();
        thesiEndiaferontos = new javax.swing.JComboBox<>();
        printFrame = new javax.swing.JFrame();
        showText = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newFile = new javax.swing.JMenuItem();
        printFile = new javax.swing.JMenuItem();
        exitFile = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();

        newFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Επώνυμο");
        newFrame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("Όνομα");
        newFrame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel3.setText("Διεύθυνση");
        newFrame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Ημερομηνία γέννησης");
        newFrame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel5.setText("Αριθμός Παιδιών");
        newFrame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        jLabel6.setText("Τίτλος Πτυχίου");
        newFrame.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        jLabel7.setText("Τίτλος Μεταπτυχιακού");
        newFrame.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 241, -1, -1));

        jLabel8.setText("Χρόνος προυπηρεσίας");
        newFrame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, -1, -1));

        jLabel9.setText("Θέση ενδιαφέροντος");
        newFrame.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        newFrame.getContentPane().add(imerominiaGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 125, 60, -1));
        newFrame.getContentPane().add(dieuthinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 87, 60, -1));
        newFrame.getContentPane().add(onoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 49, 60, -1));
        newFrame.getContentPane().add(eponymo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 11, 60, -1));
        newFrame.getContentPane().add(arithmosPaidiwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 163, 60, -1));
        newFrame.getContentPane().add(titlosPtyxiou, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 60, -1));
        newFrame.getContentPane().add(titlosMetaptixiakou, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 238, 59, -1));

        xronosProypiresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xronosProypiresiasActionPerformed(evt);
            }
        });
        newFrame.getContentPane().add(xronosProypiresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 276, 60, -1));

        jLabel10.setText("Βαθμός Πτυχίου");
        newFrame.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel11.setText("Ημερομηνία Απόκτησης Πτυχίου");
        newFrame.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));
        newFrame.getContentPane().add(vathmosPtyxiou, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 60, -1));
        newFrame.getContentPane().add(imerominiaPtyxiou, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 59, -1));

        jLabel12.setText("Ημερομηνία Απόκτησης Μεταπτυχιακού");
        newFrame.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, 20));

        imerominiaMetaptyxiakou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imerominiaMetaptyxiakouActionPerformed(evt);
            }
        });
        newFrame.getContentPane().add(imerominiaMetaptyxiakou, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, 30));

        thesiEndiaferontos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Μπυραρία", "Σουβλατζίδικο", "Καφετέρια" }));
        newFrame.getContentPane().add(thesiEndiaferontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 317, 110, -1));

        javax.swing.GroupLayout printFrameLayout = new javax.swing.GroupLayout(printFrame.getContentPane());
        printFrame.getContentPane().setLayout(printFrameLayout);
        printFrameLayout.setHorizontalGroup(
            printFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(printFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(printFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showText, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        printFrameLayout.setVerticalGroup(
            printFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(printFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(printFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showText, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        file.setText("File");

        newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFile.setText("New");
        newFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newFileMouseClicked(evt);
            }
        });
        newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileActionPerformed(evt);
            }
        });
        file.add(newFile);

        printFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printFile.setText("Print");
        printFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFileActionPerformed(evt);
            }
        });
        file.add(printFile);

        exitFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitFile.setText("Exit");
        file.add(exitFile);

        jMenuBar1.add(file);

        about.setText("About");
        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imerominiaMetaptyxiakouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imerominiaMetaptyxiakouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imerominiaMetaptyxiakouActionPerformed

    private void xronosProypiresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xronosProypiresiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xronosProypiresiasActionPerformed

    private void newFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileMouseClicked

    private void newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileActionPerformed
        // TODO add your handling code here:
        newFrame.setVisible(true) ;
        newFrame.setSize(750, 750) ;
    }//GEN-LAST:event_newFileActionPerformed

    private void printFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFileActionPerformed
        // TODO add your handling code here:
        imerominiaGenF = Integer.parseInt(imerominiaGen.getText()) ;
        dieuthinsiF = dieuthinsi.getText() ;
        onomaF = onoma.getText() ;
        eponymoF = eponymo.getText() ;
        arithmosPaidiwnF = Integer.parseInt(arithmosPaidiwn.getText()) ;
        titlosPtyxiouF = titlosPtyxiou.getText() ;
        titlosMetaptyxiakouF = titlosMetaptixiakou.getText() ;
        vathmosPtyxiouF = Double.parseDouble(vathmosPtyxiou.getText()) ;
        xronosProypiresiasF = Integer.parseInt(xronosProypiresias.getText()) ;
        vathmosPtyxiouF = Integer.parseInt(vathmosPtyxiou.getText()) ;
        imerominiaPtyxiouF = Integer.parseInt(imerominiaPtyxiou.getText()) ;
        imerominiaMetaptyxiakouF = Integer.parseInt(imerominiaMetaptyxiakou.getText()) ;
        thesiEndiaferontosF = thesiEndiaferontos.getSelectedItem().toString() ;
        double vathmos = 0 ;
        String text = "" ; 
        if(2019 - imerominiaGenF < 23)
        {
            showText.setText("den pliri tin apodekti ilikia, einai katw twn 23 etwn") ;
        }
        else
        {
            vathmos += arithmosPaidiwnF * 2 ; 
            vathmos += vathmosPtyxiouF ;
            text += "to atomo pliri ta oria ilikias, onomazetai " + onomaF + "  " + eponymoF + "\n" + "dikaioutai " + arithmosPaidiwnF * 2 + " vathmous apo ton arithmo twn paidiwn tou kai " + vathmosPtyxiouF + " vathmous apo ton vathmo ptyxiou poy exei." + "\n" ;
            if(2019 - imerominiaMetaptyxiakouF <= 10)
            {
                text += "Epipleon dikaioutai 10 vathmous apo to prosfato metaptyxiako poy exei kanei" ;
                vathmos += 10 ; 
            }
            else
            {
                text += "Epipleon dikaioutai 5 vathmous apo to metaptyxiako poy exei kanei " ;
                vathmos += 5 ; 
            }
            text+= "kathws kai " + xronosProypiresiasF * 2 + " vathmous apo ton xrono proupiresias tou" + "\n" ;
            vathmos += xronosProypiresiasF * 2 ; 
        }
        text += "SYNOLIKOI VATHMOI GIA THESI STO " + thesiEndiaferontosF + " : " + vathmos ;
        printFrame.setVisible(true) ;
        printFrame.setSize(750, 750) ;
        showText.setText(text) ;
    }//GEN-LAST:event_printFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JTextField arithmosPaidiwn;
    private javax.swing.JTextField dieuthinsi;
    private javax.swing.JTextField eponymo;
    private javax.swing.JMenuItem exitFile;
    private javax.swing.JMenu file;
    private javax.swing.JTextField imerominiaGen;
    private javax.swing.JTextField imerominiaMetaptyxiakou;
    private javax.swing.JTextField imerominiaPtyxiou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newFile;
    private javax.swing.JFrame newFrame;
    private javax.swing.JTextField onoma;
    private javax.swing.JMenuItem printFile;
    private javax.swing.JFrame printFrame;
    private javax.swing.JLabel showText;
    private javax.swing.JComboBox<String> thesiEndiaferontos;
    private javax.swing.JTextField titlosMetaptixiakou;
    private javax.swing.JTextField titlosPtyxiou;
    private javax.swing.JTextField vathmosPtyxiou;
    private javax.swing.JTextField xronosProypiresias;
    // End of variables declaration//GEN-END:variables
    private int imerominiaGenF ;
    private String dieuthinsiF = "";
    private String onomaF = "" ; 
    private String eponymoF = "" ; 
    private int arithmosPaidiwnF = 0 ;
    private String titlosPtyxiouF = ""; 
    private String titlosMetaptyxiakouF = "" ;
    private int xronosProypiresiasF = 0 ; 
    private double vathmosPtyxiouF = 0 ;
    private int imerominiaPtyxiouF ;
    private int imerominiaMetaptyxiakouF ;
    private String thesiEndiaferontosF = ""; 
}
