import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
public class Ask91 extends javax.swing.JFrame {

    /** Creates new form Ask91 */
    public Ask91() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        OpenFileText = new javax.swing.JTextField();
        Open = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        SaveDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        SaveFileText = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        SaveCancelButton = new javax.swing.JButton();
        AboutDialog = new javax.swing.JDialog();
        photoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AboutTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        message = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenFile = new javax.swing.JMenuItem();
        CloseFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SaveFile = new javax.swing.JMenuItem();
        SaveAsFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ExitFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CopyEdit = new javax.swing.JMenuItem();
        PasteEdit = new javax.swing.JMenuItem();
        CutEdit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AboutHelp = new javax.swing.JMenuItem();

        OpenDialog.setTitle("Open File");

        jLabel1.setText("Ορίστε το όνομα και τη διαδρομή του αρχείου");

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpenDialogLayout = new javax.swing.GroupLayout(OpenDialog.getContentPane());
        OpenDialog.getContentPane().setLayout(OpenDialogLayout);
        OpenDialogLayout.setHorizontalGroup(
            OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpenFileText)
                    .addGroup(OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(OpenDialogLayout.createSequentialGroup()
                            .addComponent(Open)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancel))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        OpenDialogLayout.setVerticalGroup(
            OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(OpenFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Open)
                    .addComponent(Cancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        SaveDialog.setTitle("Save File");

        jLabel2.setText("Ορίστε το όνομα και τη διαδρομή του αρχείου");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        SaveCancelButton.setText("Cancel");
        SaveCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaveDialogLayout = new javax.swing.GroupLayout(SaveDialog.getContentPane());
        SaveDialog.getContentPane().setLayout(SaveDialogLayout);
        SaveDialogLayout.setHorizontalGroup(
            SaveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SaveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SaveFileText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SaveDialogLayout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaveDialogLayout.setVerticalGroup(
            SaveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(SaveFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SaveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(SaveCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AboutDialog.setTitle("Info Details");

        photoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/582405-200.png"))); // NOI18N

        AboutTextArea.setColumns(10);
        AboutTextArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AboutTextArea.setRows(5);
        AboutTextArea.setText("Η εφαρμογη αυτη \nυλοποιηθηκε απο τον \nΣτινη Γεωργιο στις 24 \nΝοεμβριου 2016");
        jScrollPane2.setViewportView(AboutTextArea);

        javax.swing.GroupLayout AboutDialogLayout = new javax.swing.GroupLayout(AboutDialog.getContentPane());
        AboutDialog.getContentPane().setLayout(AboutDialogLayout);
        AboutDialogLayout.setHorizontalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        AboutDialogLayout.setVerticalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(photoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Menu Editor");

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        OpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenFile.setMnemonic('O');
        OpenFile.setText("Open");
        OpenFile.setToolTipText("Open a Text File");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(OpenFile);

        CloseFile.setMnemonic('C');
        CloseFile.setText("Close");
        CloseFile.setToolTipText("Close the file");
        CloseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFileActionPerformed(evt);
            }
        });
        jMenu1.add(CloseFile);
        jMenu1.add(jSeparator1);

        SaveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveFile.setMnemonic('S');
        SaveFile.setText("Save");
        SaveFile.setToolTipText("Save the File");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        jMenu1.add(SaveFile);

        SaveAsFile.setMnemonic('A');
        SaveAsFile.setText("Save As");
        SaveAsFile.setToolTipText("Save file with a new name");
        SaveAsFile.setDisplayedMnemonicIndex(5);
        SaveAsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsFileActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAsFile);
        jMenu1.add(jSeparator2);

        ExitFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitFile.setMnemonic('E');
        ExitFile.setText("Exit");
        ExitFile.setToolTipText("Close the application");
        ExitFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitFileActionPerformed(evt);
            }
        });
        jMenu1.add(ExitFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");

        CopyEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CopyEdit.setMnemonic('C');
        CopyEdit.setText("Copy");
        CopyEdit.setToolTipText("Copy to clipboard");
        CopyEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyEditActionPerformed(evt);
            }
        });
        jMenu2.add(CopyEdit);

        PasteEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PasteEdit.setMnemonic('P');
        PasteEdit.setText("Paste");
        PasteEdit.setToolTipText("Paste text from clipboard");
        PasteEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteEditActionPerformed(evt);
            }
        });
        jMenu2.add(PasteEdit);

        CutEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        CutEdit.setMnemonic('U');
        CutEdit.setText("Cut");
        CutEdit.setToolTipText("Cut to clipboard");
        CutEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutEditActionPerformed(evt);
            }
        });
        jMenu2.add(CutEdit);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('H');
        jMenu3.setText("Help");

        AboutHelp.setMnemonic('A');
        AboutHelp.setText("About");
        AboutHelp.setToolTipText("Info about the developer");
        AboutHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutHelpActionPerformed(evt);
            }
        });
        jMenu3.add(AboutHelp);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        OpenDialog.setVisible(true);
        OpenDialog.setSize(300, 200);
    }//GEN-LAST:event_OpenFileActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        FileReader fw;
        filename=OpenFileText.getText();
        if (filename.length()==0){
            message.setText("Ορίστε το όνομα και τη διαδρομή του αρχείου που θέλετε να ανοίξετε");
            OpenDialog.setVisible(false);
            return;
        }
        try {
            fw= new FileReader(filename);
            jTextArea1.read(fw, null);
            fw.close();
            OpenDialog.setVisible(false);
            setTitle(filename);
        }
        catch (IOException exc){
            message.setText("Λάθος όνομα αρχείου.");
            return;
        }
        message.setText("Το αρχείο φορτώθηκε σωστά.");
    }//GEN-LAST:event_OpenActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        OpenDialog.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void CloseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFileActionPerformed
        jTextArea1.setText("");
        filename="";
        setTitle("Simple Menu Editor");
    }//GEN-LAST:event_CloseFileActionPerformed

    private void SaveAsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsFileActionPerformed
        SaveDialog.setVisible(true);
        SaveDialog.setSize(300, 200);
    }//GEN-LAST:event_SaveAsFileActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        FileWriter fw;
        filename=SaveFileText.getText();
        if (filename.length()==0){
            message.setText("Ορίστε το όνομα και τη διαδρομή του αρχείου που θέλετε να αποθηκεύσετε");
            SaveDialog.setVisible(false);
            return;
        }
        try {
            fw= new FileWriter(filename);
            jTextArea1.write(fw);
            fw.close();
            SaveDialog.setVisible(false);
            setTitle(filename);
        }
        catch (IOException exc){
            message.setText("Λάθος όνομα αρχείου.");
            return;
        }
        message.setText("Το αρχείο αποθηκεύτηκε σωστά.");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SaveCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCancelButtonActionPerformed
        SaveDialog.setVisible(false);
    }//GEN-LAST:event_SaveCancelButtonActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        FileWriter fw;
        if (filename==""){
            SaveAsFile.doClick();
        }
        else {
            try{
                fw= new FileWriter(filename);
                jTextArea1.write(fw);
                fw.close();
                message.setText("Το αρχείο αποθηκεύτηκε σωστά.");
            }
            catch (IOException exc){
                message.setText(exc.getMessage());
            }
        }
    }//GEN-LAST:event_SaveFileActionPerformed

    private void ExitFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitFileActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitFileActionPerformed

    private void CopyEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyEditActionPerformed
        jTextArea1.copy();
    }//GEN-LAST:event_CopyEditActionPerformed

    private void PasteEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteEditActionPerformed
        jTextArea1.paste();
    }//GEN-LAST:event_PasteEditActionPerformed

    private void CutEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutEditActionPerformed
        jTextArea1.cut();
    }//GEN-LAST:event_CutEditActionPerformed

    private void AboutHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutHelpActionPerformed
        AboutDialog.setVisible(true);
        AboutDialog.setSize(500,250);
    }//GEN-LAST:event_AboutHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ask91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ask91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ask91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ask91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ask91().setVisible(true);
            }
        });
    }
    String filename="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutDialog;
    private javax.swing.JMenuItem AboutHelp;
    private javax.swing.JTextArea AboutTextArea;
    private javax.swing.JButton Cancel;
    private javax.swing.JMenuItem CloseFile;
    private javax.swing.JMenuItem CopyEdit;
    private javax.swing.JMenuItem CutEdit;
    private javax.swing.JMenuItem ExitFile;
    private javax.swing.JButton Open;
    private javax.swing.JDialog OpenDialog;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JTextField OpenFileText;
    private javax.swing.JMenuItem PasteEdit;
    private javax.swing.JMenuItem SaveAsFile;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SaveCancelButton;
    private javax.swing.JDialog SaveDialog;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JTextField SaveFileText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables
}
