/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gsak3
 */
public class StockFrame extends javax.swing.JFrame {

    /**
     * Creates new form StockFrame
     */
    public StockFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        o1 = new javax.swing.JTextField();
        o2 = new javax.swing.JTextField();
        o3 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        javaRight = new javax.swing.JLabel();
        owlRight = new javax.swing.JLabel();
        basicRight = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Βρες την λέξη και κέρδισε βραβείο!!");

        jLabel2.setText("Προσπάθειες που απομένουν : 6 ");

        jLabel3.setText("Hint : Είναι γλώσσες προγραμματισμού");

        j1.setEditable(false);
        j1.setText("J");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setText("_");
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        j2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j2KeyReleased(evt);
            }
        });

        j3.setText("_");
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });
        j3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j3KeyReleased(evt);
            }
        });

        j4.setText("_");
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        j4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j4KeyReleased(evt);
            }
        });

        o1.setEditable(false);
        o1.setText("O");

        o2.setText("_");
        o2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o2MouseClicked(evt);
            }
        });
        o2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                o2KeyReleased(evt);
            }
        });

        o3.setText("_");
        o3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o3MouseClicked(evt);
            }
        });
        o3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                o3KeyReleased(evt);
            }
        });

        b1.setText("B");

        b2.setText("_");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b2KeyReleased(evt);
            }
        });

        b3.setText("_");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b3KeyReleased(evt);
            }
        });

        b4.setText("_");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b4KeyReleased(evt);
            }
        });

        b5.setText("_");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j1)
                                    .addComponent(b1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(o2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(owlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(javaRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(basicRight, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4)
                            .addComponent(javaRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owlRight, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basicRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        // TODO add your handling code here:
        j2.setText("") ;
        if(j3.getText().equals("") || j3.getText().equals(" "))
        {
            j3.setText("_") ;
        }
        if(j4.getText().equals("") || j4.getText().equals(" "))
        {
            j4.setText("_") ;
        }
    }//GEN-LAST:event_j2MouseClicked

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        // TODO add your handling code here:
        j3.setText("") ;
        if(j2.getText().equals("") || j2.getText().equals(" "))
        {
            j2.setText("_") ;
        }
        if(j4.getText().equals("") || j4.getText().equals(" "))
        {
            j4.setText("_") ;
        }
    }//GEN-LAST:event_j3MouseClicked

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
        // TODO add your handling code here:
        j4.setText("") ;
        if(j3.getText().equals("") || j3.getText().equals(" "))
        {
            j3.setText("_") ;
        }
        if(j2.getText().equals("") || j2.getText().equals(" "))
        {
            j2.setText("_") ;
        }
    }//GEN-LAST:event_j4MouseClicked

    private void o2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o2MouseClicked
        // TODO add your handling code here:
        o2.setText("") ;
        if(o3.getText().equals("") || o3.getText().equals(" "))
        {
            o3.setText("_") ;
        }
    }//GEN-LAST:event_o2MouseClicked

    private void o3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o3MouseClicked
        // TODO add your handling code here:
        o3.setText("") ;
        if(o2.getText().equals("") || o2.getText().equals(" "))
        {
            o2.setText("_") ;
        }
    }//GEN-LAST:event_o3MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
        b2.setText("") ;
        if(b3.getText().equals("") || b3.getText().equals(" "))
        {
            b3.setText("_") ;
        }
        if(b4.getText().equals("") || b4.getText().equals(" "))
        {
            b4.setText("_") ;
        }
        if(b5.getText().equals("") || b5.getText().equals(" "))
        {
            b5.setText("_") ;
        }
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
        b3.setText("") ;
        if(b2.getText().equals("") || b2.getText().equals(" "))
        {
            b2.setText("_") ;
        }
        if(b4.getText().equals("") || b4.getText().equals(" "))
        {
            b4.setText("_") ;
        }
        if(b5.getText().equals("") || b5.getText().equals(" "))
        {
            b5.setText("_") ;
        }
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // TODO add your handling code here:
        b4.setText("") ;
        if(b3.getText().equals("") || b3.getText().equals(" "))
        {
            b3.setText("_") ;
        }
        if(b2.getText().equals("") || b2.getText().equals(" "))
        {
            b2.setText("_") ;
        }
        if(b5.getText().equals("") || b5.getText().equals(" "))
        {
            b5.setText("_") ;
        }
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        // TODO add your handling code here:
        b5.setText("") ;
        if(b3.getText().equals("") || b3.getText().equals(" "))
        {
            b3.setText("_") ;
        }
        if(b4.getText().equals("") || b4.getText().equals(" "))
        {
            b4.setText("_") ;
        }
        if(b2.getText().equals("") || b2.getText().equals(" "))
        {
            b2.setText("_") ;
        }
    }//GEN-LAST:event_b5MouseClicked

    private void j2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j2KeyReleased
        // TODO add your handling code here:
        if(j2.getText().equals("1") || j2.getText().equals("2") || j2.getText().equals("3") || j2.getText().equals("4") || j2.getText().equals("5") || j2.getText().equals("6") || j2.getText().equals("7") || j2.getText().equals("8") || j2.getText().equals("9"))
        {
            j2.setText("") ;
        }
        if(j2.getText().length() > 1)
        {
            j2.setText("") ;
        }
        javaWord += j2.getText().toUpperCase() ;
        if(javaWord.length() == 4)
        {
            if(javaWord.equals("JAVA"))
            {
             rightWords ++ ;
             j1.setEnabled(false) ;
             j2.setEnabled(false) ;
             j3.setEnabled(false) ;
             j4.setEnabled(false) ;
             javaRight.setText("CORRECT!") ;
             jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
              counter -- ; 
              jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
              j2.setText("_") ;
              j3.setText("_") ;
              j4.setText("_") ;
              javaWord = "J" ;
            }
        }
    }//GEN-LAST:event_j2KeyReleased

    private void j3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j3KeyReleased
        // TODO add your handling code here:
        if(j3.getText().equals("1") || j3.getText().equals("2") || j3.getText().equals("3") || j3.getText().equals("4") || j3.getText().equals("5") || j3.getText().equals("6") || j3.getText().equals("7") || j3.getText().equals("8") || j3.getText().equals("9"))
        {
            j3.setText("") ;
        }
        if(j3.getText().length() > 1)
        {
            j3.setText("") ;
        }
        javaWord += j3.getText().toUpperCase() ;
        if(javaWord.length() == 4)
        {
            if(javaWord.equals("JAVA"))
            {
             rightWords ++ ;
             j1.setEnabled(false) ;
             j2.setEnabled(false) ;
             j3.setEnabled(false) ;
             j4.setEnabled(false) ;
             javaRight.setText("CORRECT!") ;
             jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
              counter -- ; 
              jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
              j2.setText("_") ;
              j3.setText("_") ;
              j4.setText("_") ;
              javaWord = "J" ;
            }
        }
    }//GEN-LAST:event_j3KeyReleased

    private void j4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j4KeyReleased
        // TODO add your handling code here:
        if(j4.getText().equals("1") || j4.getText().equals("2") || j4.getText().equals("3") || j4.getText().equals("4") || j4.getText().equals("5") || j4.getText().equals("6") || j4.getText().equals("7") || j4.getText().equals("8") || j4.getText().equals("9"))
        {
            j4.setText("") ;
        }
        if(j4.getText().length() > 1)
        {
            j4.setText("") ;
        }
        javaWord += j4.getText().toUpperCase() ;
        if(javaWord.length() == 4)
        {
            if(javaWord.equals("JAVA"))
            {
             rightWords ++ ;
             j1.setEnabled(false) ;
             j2.setEnabled(false) ;
             j3.setEnabled(false) ;
             j4.setEnabled(false) ;
             javaRight.setText("CORRECT!") ;
             jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
              counter -- ; 
              jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
              j2.setText("_") ;
              j3.setText("_") ;
              j4.setText("_") ;
              javaWord = "J" ;
            }
        }
    }//GEN-LAST:event_j4KeyReleased

    private void o2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o2KeyReleased
        // TODO add your handling code here:
        if(o2.getText().equals("1") || o2.getText().equals("2") || o2.getText().equals("3") || o2.getText().equals("4") || o2.getText().equals("5") || o2.getText().equals("6") || o2.getText().equals("7") || o2.getText().equals("8") || o2.getText().equals("9"))
        {
            o2.setText("") ;
        }
        if(o2.getText().length() > 1)
        {
            o2.setText("") ;
        }
        owlWord += o2.getText().toUpperCase() ;
        if(owlWord.length() == 3)
        {
            if(owlWord.equals("OWL"))
            {
                rightWords ++ ;
                o1.setEnabled(false) ;
                o2.setEnabled(false) ;
                o3.setEnabled(false) ;
                owlRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ;
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                o2.setText("_") ;
                o3.setText("_") ;
                owlWord = "O" ;
            }
        }
    }//GEN-LAST:event_o2KeyReleased

    private void o3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o3KeyReleased
        // TODO add your handling code here:
        if(o3.getText().equals("1") || o3.getText().equals("2") || o3.getText().equals("3") || o3.getText().equals("4") || o3.getText().equals("5") || o3.getText().equals("6") || o3.getText().equals("7") || o3.getText().equals("8") || o3.getText().equals("9"))
        {
            o3.setText("") ;
        }
        if(o3.getText().length() > 1)
        {
            o3.setText("") ;
        }
        owlWord += o3.getText().toUpperCase() ;
        if(owlWord.length() == 3)
        {
            if(owlWord.equals("OWL"))
            {
                rightWords ++ ;
                o1.setEnabled(false) ;
                o2.setEnabled(false) ;
                o3.setEnabled(false) ;
                owlRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ;
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                o2.setText("_") ;
                o3.setText("_") ;
                owlWord = "O" ;
            }
        }
    }//GEN-LAST:event_o3KeyReleased

    private void b2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyReleased
        // TODO add your handling code here:
        if(b2.getText().equals("1") || b2.getText().equals("2") || b2.getText().equals("3") || b2.getText().equals("4") || b2.getText().equals("5") || b2.getText().equals("6") || b2.getText().equals("7") || b2.getText().equals("8") || b2.getText().equals("9"))
        {
            b2.setText("") ;
        }
        if(b2.getText().length() > 1)
        {
            b2.setText("") ;
        }
        basicWord += b2.getText().toUpperCase() ; 
        if(basicWord.length() == 5)
        {
            if(basicWord.equals("BASIC"))
            {
                rightWords++ ; 
                b1.setEnabled(false) ;
                b2.setEnabled(false) ;
                b3.setEnabled(false) ;
                b4.setEnabled(false) ;
                b5.setEnabled(false) ;
                basicRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ; 
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                b2.setText("_") ;
                b3.setText("_") ;
                b4.setText("_") ;
                b5.setText("_") ;
                basicWord = "B" ;
            }
        }
    }//GEN-LAST:event_b2KeyReleased

    private void b3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b3KeyReleased
        // TODO add your handling code here:
        if(b3.getText().equals("1") || b3.getText().equals("2") || b3.getText().equals("3") || b3.getText().equals("4") || b3.getText().equals("5") || b3.getText().equals("6") || b3.getText().equals("7") || b3.getText().equals("8") || b3.getText().equals("9"))
        {
            b3.setText("") ;
        }
        if(b3.getText().length() > 1)
        {
            b3.setText("") ;
        }
        basicWord += b3.getText().toUpperCase() ;
        if(basicWord.length() == 5)
        {
            if(basicWord.equals("BASIC"))
            {
                rightWords++ ; 
                b1.setEnabled(false) ;
                b2.setEnabled(false) ;
                b3.setEnabled(false) ;
                b4.setEnabled(false) ;
                b5.setEnabled(false) ;
                basicRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ; 
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                b2.setText("_") ;
                b3.setText("_") ;
                b4.setText("_") ;
                b5.setText("_") ;
                basicWord = "B" ;
            }
        }
    }//GEN-LAST:event_b3KeyReleased

    private void b4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b4KeyReleased
        // TODO add your handling code here:
        if(b4.getText().equals("1") || b4.getText().equals("2") || b4.getText().equals("3") || b4.getText().equals("4") || b4.getText().equals("5") || b4.getText().equals("6") || b4.getText().equals("7") || b4.getText().equals("8") || b4.getText().equals("9"))
        {
            b4.setText("") ;
        }
        if(b4.getText().length() > 1)
        {
            b4.setText("") ;
        }
        basicWord += b4.getText().toUpperCase() ;
        if(basicWord.length() == 5)
        {
            if(basicWord.equals("BASIC"))
            {
                rightWords++ ; 
                b1.setEnabled(false) ;
                b2.setEnabled(false) ;
                b3.setEnabled(false) ;
                b4.setEnabled(false) ;
                b5.setEnabled(false) ;
                basicRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ; 
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                b2.setText("_") ;
                b3.setText("_") ;
                b4.setText("_") ;
                b5.setText("_") ;
                basicWord = "B" ;
            }
        }
    }//GEN-LAST:event_b4KeyReleased

    private void b5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyReleased
        // TODO add your handling code here:
        if(b5.getText().equals("1") || b5.getText().equals("2") || b5.getText().equals("3") || b5.getText().equals("4") || b5.getText().equals("5") || b5.getText().equals("6") || b5.getText().equals("7") || b5.getText().equals("8") || b5.getText().equals("9"))
        {
            b5.setText("") ;
        }
        if(b5.getText().length() > 1)
        {
            b5.setText("") ;
        }
        basicWord += b5.getText().toUpperCase() ;
        if(basicWord.length() == 5)
        {
            if(basicWord.equals("BASIC"))
            {
                rightWords++ ; 
                b1.setEnabled(false) ;
                b2.setEnabled(false) ;
                b3.setEnabled(false) ;
                b4.setEnabled(false) ;
                b5.setEnabled(false) ;
                basicRight.setText("CORRECT!") ;
                jLabel5.setText("Βρήκες σωστές " + rightWords + " λέξεις") ;
            }
            else
            {
                counter -- ; 
                jLabel2.setText("Προσπάθειες που απομένουν : " + counter) ;
                b2.setText("_") ;
                b3.setText("_") ;
                b4.setText("_") ;
                b5.setText("_") ;
                basicWord = "B" ;
            }
        }
    }//GEN-LAST:event_b5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JLabel basicRight;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel javaRight;
    private javax.swing.JTextField o1;
    private javax.swing.JTextField o2;
    private javax.swing.JTextField o3;
    private javax.swing.JLabel owlRight;
    // End of variables declaration//GEN-END:variables
    private String javaWord = "J" ;
    private String owlWord = "O" ; 
    private String basicWord = "B" ;
    private int counter = 6 ; 
    private int rightWords = 0 ; 
}
