
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hollidays.java
 *
 * Created on Oct 29, 2018, 11:31:30 AM
 */
/**
 *
 * @author user
 */
public class Hollidays extends javax.swing.JFrame {

    /** Creates new form Hollidays */
    public Hollidays() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPHotels = new javax.swing.JPanel();
        jRBALArab = new javax.swing.JRadioButton();
        jRBHilton = new javax.swing.JRadioButton();
        jRBIceHotel = new javax.swing.JRadioButton();
        jPDetails = new javax.swing.JPanel();
        Breakfast = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JCheckBox();
        ExtraTrip = new javax.swing.JCheckBox();
        jPRoom = new javax.swing.JPanel();
        jRBSingle = new javax.swing.JRadioButton();
        jRBDouble = new javax.swing.JRadioButton();
        jRBSuite = new javax.swing.JRadioButton();
        jBShowIcon = new javax.swing.JButton();
        Room = new javax.swing.JLabel();
        jPReport = new javax.swing.JPanel();
        jLHotel = new javax.swing.JLabel();
        jLRoom = new javax.swing.JLabel();
        jLDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRBALArab);
        jRBALArab.setSelected(true);
        jRBALArab.setToolTipText("Al Arab Hotel");
        jRBALArab.setIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\BurjAlArabHotelBW.jpg")); // NOI18N
        jRBALArab.setPressedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\BurjAlArabHotel.jpg")); // NOI18N
        jRBALArab.setRolloverIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\BurjAlArabHotel.jpg")); // NOI18N
        jRBALArab.setSelectedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\BurjAlArabHotel.jpg")); // NOI18N
        jRBALArab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBALArabItemStateChanged(evt);
            }
        });
        jRBALArab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBALArabActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBHilton);
        jRBHilton.setToolTipText("Hilton");
        jRBHilton.setIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\hiltonhotelBW.jpg")); // NOI18N
        jRBHilton.setPressedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\hiltonhotel.jpg")); // NOI18N
        jRBHilton.setRolloverIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\hiltonhotel.jpg")); // NOI18N
        jRBHilton.setSelectedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\hiltonhotel.jpg")); // NOI18N
        jRBHilton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBHiltonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRBIceHotel);
        jRBIceHotel.setToolTipText("Ice Hotel");
        jRBIceHotel.setIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\icehotelBW.jpg")); // NOI18N
        jRBIceHotel.setPressedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\icehotel.jpg")); // NOI18N
        jRBIceHotel.setRolloverIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\icehotel.jpg")); // NOI18N
        jRBIceHotel.setSelectedIcon(new javax.swing.ImageIcon("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\icehotel.jpg")); // NOI18N
        jRBIceHotel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBIceHotelItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPHotelsLayout = new javax.swing.GroupLayout(jPHotels);
        jPHotels.setLayout(jPHotelsLayout);
        jPHotelsLayout.setHorizontalGroup(
            jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelsLayout.createSequentialGroup()
                .addGroup(jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPHotelsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRBALArab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPHotelsLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jRBIceHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPHotelsLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jRBHilton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPHotelsLayout.setVerticalGroup(
            jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jRBALArab, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBHilton)
                .addGap(18, 18, 18)
                .addComponent(jRBIceHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPHotels);

        jTabbedPane1.addTab("Hotels", jScrollPane1);

        jPDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPDetailsFocusGained(evt);
            }
        });

        Breakfast.setText("Breakfast");
        Breakfast.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BreakfastItemStateChanged(evt);
            }
        });

        Dinner.setText("Dinner");
        Dinner.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DinnerItemStateChanged(evt);
            }
        });
        Dinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinnerActionPerformed(evt);
            }
        });

        buttonGroup3.add(ExtraTrip);
        ExtraTrip.setText("Extra Trip");
        ExtraTrip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ExtraTripItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPDetailsLayout = new javax.swing.GroupLayout(jPDetails);
        jPDetails.setLayout(jPDetailsLayout);
        jPDetailsLayout.setHorizontalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dinner)
                    .addComponent(Breakfast)
                    .addComponent(ExtraTrip))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPDetailsLayout.setVerticalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Breakfast)
                .addGap(35, 35, 35)
                .addComponent(Dinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ExtraTrip)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Details", jPDetails);

        buttonGroup3.add(jRBSingle);
        jRBSingle.setText("Single");
        jRBSingle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBSingleItemStateChanged(evt);
            }
        });

        buttonGroup3.add(jRBDouble);
        jRBDouble.setText("Double");
        jRBDouble.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBDoubleItemStateChanged(evt);
            }
        });

        buttonGroup3.add(jRBSuite);
        jRBSuite.setText("Suite");
        jRBSuite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBSuiteItemStateChanged(evt);
            }
        });

        jBShowIcon.setText("Show Icon");
        jBShowIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBShowIconActionPerformed(evt);
            }
        });

        Room.setMaximumSize(new java.awt.Dimension(120, 100));
        Room.setMinimumSize(new java.awt.Dimension(120, 100));
        Room.setPreferredSize(new java.awt.Dimension(120, 100));

        javax.swing.GroupLayout jPRoomLayout = new javax.swing.GroupLayout(jPRoom);
        jPRoom.setLayout(jPRoomLayout);
        jPRoomLayout.setHorizontalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBSingle)
                    .addComponent(jRBDouble)
                    .addComponent(jRBSuite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBShowIcon))
                .addGap(99, 99, 99))
        );
        jPRoomLayout.setVerticalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSingle)
                    .addComponent(jBShowIcon))
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jRBDouble)
                        .addGap(46, 46, 46)
                        .addComponent(jRBSuite))
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Room", jPRoom);

        jLHotel.setText("jLabel2");

        jLRoom.setText("jLabel3");

        jLDetails.setText("jLabel4");

        javax.swing.GroupLayout jPReportLayout = new javax.swing.GroupLayout(jPReport);
        jPReport.setLayout(jPReportLayout);
        jPReportLayout.setHorizontalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addGroup(jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jLRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jLDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPReportLayout.setVerticalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRBALArabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBALArabActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRBALArabActionPerformed

private void DinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinnerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DinnerActionPerformed

private void jRBALArabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBALArabItemStateChanged
    jLHotel.setText("To epilegmeno ksenodoxeio einai to AL Arab");
}//GEN-LAST:event_jRBALArabItemStateChanged

private void jRBHiltonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBHiltonItemStateChanged
    jLHotel.setText("To epilegmeno ksenodoxeio einai to Hilton");
}//GEN-LAST:event_jRBHiltonItemStateChanged

private void jRBIceHotelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBIceHotelItemStateChanged
    jLHotel.setText("To epilegmeno ksenodoxeio einai to Ice Hotel");
}//GEN-LAST:event_jRBIceHotelItemStateChanged

private void BreakfastItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BreakfastItemStateChanged
    String infodetails="";
    if(Breakfast.isSelected()) infodetails+="Breakfast ";
    if(Dinner.isSelected()) infodetails +="Dinner ";
    if(ExtraTrip.isSelected()) infodetails +="Extra Trip ";
    jLDetails.setText("Epilogh paketou: "+infodetails);
}//GEN-LAST:event_BreakfastItemStateChanged

private void DinnerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DinnerItemStateChanged
    String infodetails="";
    if(Breakfast.isSelected()) infodetails+="Breakfast ";
    if(Dinner.isSelected()) infodetails +="Dinner ";
    if(ExtraTrip.isSelected()) infodetails +="Extra Trip ";
    jLDetails.setText("Epilogh paketou: "+infodetails);
}//GEN-LAST:event_DinnerItemStateChanged

private void ExtraTripItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ExtraTripItemStateChanged
    String infodetails="";
    if(Breakfast.isSelected()) infodetails+="Breakfast ";
    if(Dinner.isSelected()) infodetails +="Dinner ";
    if(ExtraTrip.isSelected()) infodetails +="Extra Trip ";
    jLDetails.setText("Epilogh paketou: "+infodetails);
}//GEN-LAST:event_ExtraTripItemStateChanged

private void jRBSingleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBSingleItemStateChanged
    jLRoom.setText("O epilegmenos tupos dwmatiou einai mono");
}//GEN-LAST:event_jRBSingleItemStateChanged

private void jRBDoubleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBDoubleItemStateChanged
    jLRoom.setText("O epilegmenos tupos dwmatiou einai diplo");
}//GEN-LAST:event_jRBDoubleItemStateChanged

private void jRBSuiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBSuiteItemStateChanged
    jLRoom.setText("O epilegmenos tupos dwmatiou einai suita");
}//GEN-LAST:event_jRBSuiteItemStateChanged

private void jBShowIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBShowIconActionPerformed
    if(jRBALArab.isSelected()){
        if(jRBSingle.isSelected())
            Room.setIcon(BAAHSingle);
        else if (jRBDouble.isSelected())
            Room.setIcon(BAAHDouble);
        else if (jRBSuite.isSelected())
            Room.setIcon(BAAHSuite);
    }
    else if (jRBHilton.isSelected()){
        if(jRBSingle.isSelected())
            Room.setIcon(HiltonSingle);
        else if (jRBDouble.isSelected())
            Room.setIcon(HiltonDouble);
        else if (jRBSuite.isSelected())
            Room.setIcon(HiltonSuite);
    }
    else if(jRBIceHotel.isSelected()){
        if(jRBSingle.isSelected())
            Room.setIcon(IceHotelSingle);
        else if (jRBDouble.isSelected())
            Room.setIcon(IceHotelDouble);
        else if (jRBSuite.isSelected())
            Room.setIcon(IceHotelSuite);
    }
}//GEN-LAST:event_jBShowIconActionPerformed

private void jPDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPDetailsFocusGained
    if(jRBALArab.isSelected())
        jLHotel.setText("To epilegmeno ksenodoxeio einai to Al Arab");
    else if (jRBHilton.isSelected())
        jLHotel.setText("To epilegmeno ksenodoxeio einai to Hilton");
    else if(jRBIceHotel.isSelected())
        jLHotel.setText("To epilegmeno ksenodoxeio einai to Ice Hotel");
    String infodetails="";
    if(Breakfast.isSelected()) infodetails+="Breakfast ";
    if(Dinner.isSelected()) infodetails +="Dinner ";
    if(ExtraTrip.isSelected()) infodetails +="Extra Trip ";
    jLDetails.setText("Epilogh paketou: "+infodetails);
    if(jRBSingle.isSelected())
       jLRoom.setText("To dwmatio einai mono");
    else if (jRBDouble.isSelected())
        jLRoom.setText("To dwmatio einai diplo");
    else if (jRBSuite.isSelected())
        jLRoom.setText("To dwmatio einai suite");
}//GEN-LAST:event_jPDetailsFocusGained

ImageIcon BAAHSingle=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\AlArabSingle.jpg");
ImageIcon BAAHDouble=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\AlArabDouble.jpg");
ImageIcon BAAHSuite=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\AlArabSuite.jpg");
ImageIcon HiltonSingle=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\HiltonSingle.jpg");
ImageIcon HiltonDouble=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\HiltonDouble.jpg");
ImageIcon HiltonSuite=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\HiltonSuite.jpg");
ImageIcon IceHotelSuite=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\IceHotelSuite.jpg");
ImageIcon IceHotelSingle=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\IceHotelSingle.jpg");
ImageIcon IceHotelDouble=new ImageIcon ("H:\\3oeksamino\\Allhlepidrash\\ergasthrio5\\IceHotelDouble.jpg");




     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hollidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hollidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hollidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hollidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hollidays().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Breakfast;
    private javax.swing.JCheckBox Dinner;
    private javax.swing.JCheckBox ExtraTrip;
    private javax.swing.JLabel Room;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBShowIcon;
    private javax.swing.JLabel jLDetails;
    private javax.swing.JLabel jLHotel;
    private javax.swing.JLabel jLRoom;
    private javax.swing.JPanel jPDetails;
    private javax.swing.JPanel jPHotels;
    private javax.swing.JPanel jPReport;
    private javax.swing.JPanel jPRoom;
    private javax.swing.JRadioButton jRBALArab;
    private javax.swing.JRadioButton jRBDouble;
    private javax.swing.JRadioButton jRBHilton;
    private javax.swing.JRadioButton jRBIceHotel;
    private javax.swing.JRadioButton jRBSingle;
    private javax.swing.JRadioButton jRBSuite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
