/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HOLIDAYS.java
 *
 * Created on Oct 29, 2018, 7:26:45 AM
 */
/**
 *
 * @author user
 */
public class HOLIDAYS extends javax.swing.JFrame {

    /** Creates new form HOLIDAYS */
    public HOLIDAYS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPHotels = new javax.swing.JPanel();
        jRBAlarab = new javax.swing.JRadioButton();
        jRBHilton = new javax.swing.JRadioButton();
        jRBIcedHotel = new javax.swing.JRadioButton();
        jPDetails = new javax.swing.JPanel();
        Breakfast = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JCheckBox();
        ExtraTrip = new javax.swing.JCheckBox();
        jPRoom = new javax.swing.JPanel();
        jRBSinge = new javax.swing.JRadioButton();
        Double = new javax.swing.JRadioButton();
        jRBSuite = new javax.swing.JRadioButton();
        jBShowIcon = new javax.swing.JButton();
        jLRoomIcon = new javax.swing.JLabel();
        jPReport = new javax.swing.JPanel();
        jLHotel = new javax.swing.JLabel();
        jLRoom = new javax.swing.JLabel();
        jLDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRBAlarab);
        jRBAlarab.setToolTipText("Al Arab Hotel");
        jRBAlarab.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\BurjAlArabHotelBW.jpg")); // NOI18N
        jRBAlarab.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\BurjAlArabHotel.jpg")); // NOI18N

        buttonGroup1.add(jRBHilton);
        jRBHilton.setToolTipText("Hilton");
        jRBHilton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\hiltonhotelBW.jpg")); // NOI18N
        jRBHilton.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\hiltonhotel.jpg")); // NOI18N
        jRBHilton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHiltonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBIcedHotel);
        jRBIcedHotel.setToolTipText("Iced");
        jRBIcedHotel.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\icehotelBW.jpg")); // NOI18N
        jRBIcedHotel.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\HOTELS\\icehotel.jpg")); // NOI18N
        jRBIcedHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIcedHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPHotelsLayout = new javax.swing.GroupLayout(jPHotels);
        jPHotels.setLayout(jPHotelsLayout);
        jPHotelsLayout.setHorizontalGroup(
            jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHotelsLayout.createSequentialGroup()
                        .addComponent(jRBAlarab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(254, 254, 254))
                    .addGroup(jPHotelsLayout.createSequentialGroup()
                        .addGroup(jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRBHilton, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jRBIcedHotel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPHotelsLayout.setVerticalGroup(
            jPHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBAlarab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBHilton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBIcedHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPHotels);

        jTabbedPane1.addTab("HOTELS", jScrollPane1);

        Breakfast.setText("Breakfast");

        Dinner.setText("Dinner ");
        Dinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinnerActionPerformed(evt);
            }
        });

        ExtraTrip.setText("Extra Trip");

        javax.swing.GroupLayout jPDetailsLayout = new javax.swing.GroupLayout(jPDetails);
        jPDetails.setLayout(jPDetailsLayout);
        jPDetailsLayout.setHorizontalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addGroup(jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Breakfast))
                    .addGroup(jPDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dinner))
                    .addGroup(jPDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ExtraTrip)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPDetailsLayout.setVerticalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Breakfast)
                .addGap(18, 18, 18)
                .addComponent(Dinner)
                .addGap(18, 18, 18)
                .addComponent(ExtraTrip)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DETAILS", jPDetails);

        jRBSinge.setText("Single");

        Double.setText("Double");
        Double.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleActionPerformed(evt);
            }
        });

        jRBSuite.setText("Suite");

        jBShowIcon.setText("Show Icon");

        jLRoomIcon.setText("jLabel1");

        javax.swing.GroupLayout jPRoomLayout = new javax.swing.GroupLayout(jPRoom);
        jPRoom.setLayout(jPRoomLayout);
        jPRoomLayout.setHorizontalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBSinge)
                            .addComponent(Double))
                        .addGap(37, 37, 37)
                        .addComponent(jBShowIcon))
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addComponent(jRBSuite)
                        .addGap(56, 56, 56)
                        .addComponent(jLRoomIcon)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPRoomLayout.setVerticalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSinge)
                    .addComponent(jBShowIcon))
                .addGap(17, 17, 17)
                .addComponent(Double)
                .addGap(18, 18, 18)
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSuite)
                    .addComponent(jLRoomIcon))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ROOM", jPRoom);

        jLHotel.setText("jLabel2");

        jLRoom.setText("jLabel3");

        jLDetails.setText("jLabel4");

        javax.swing.GroupLayout jPReportLayout = new javax.swing.GroupLayout(jPReport);
        jPReport.setLayout(jPReportLayout);
        jPReportLayout.setHorizontalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPReportLayout.createSequentialGroup()
                        .addComponent(jLDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPReportLayout.createSequentialGroup()
                            .addComponent(jLHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPReportLayout.createSequentialGroup()
                            .addComponent(jLRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        jPReportLayout.setVerticalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLHotel)
                .addGap(18, 18, 18)
                .addComponent(jLRoom)
                .addGap(18, 18, 18)
                .addComponent(jLDetails)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REPORT", jPReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRBHiltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHiltonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRBHiltonActionPerformed

private void DinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinnerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DinnerActionPerformed

private void DoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DoubleActionPerformed

private void jRBIcedHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIcedHotelActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRBIcedHotelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOLIDAYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOLIDAYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOLIDAYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOLIDAYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HOLIDAYS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Breakfast;
    private javax.swing.JCheckBox Dinner;
    private javax.swing.JRadioButton Double;
    private javax.swing.JCheckBox ExtraTrip;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBShowIcon;
    private javax.swing.JLabel jLDetails;
    private javax.swing.JLabel jLHotel;
    private javax.swing.JLabel jLRoom;
    private javax.swing.JLabel jLRoomIcon;
    private javax.swing.JPanel jPDetails;
    private javax.swing.JPanel jPHotels;
    private javax.swing.JPanel jPReport;
    private javax.swing.JPanel jPRoom;
    private javax.swing.JRadioButton jRBAlarab;
    private javax.swing.JRadioButton jRBHilton;
    private javax.swing.JRadioButton jRBIcedHotel;
    private javax.swing.JRadioButton jRBSinge;
    private javax.swing.JRadioButton jRBSuite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
