
import java.util.Hashtable;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Nov 6, 2019, 10:37:30 AM
 */
/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }
    Hashtable table = new Hashtable();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lBass = new javax.swing.JLabel();
        lMidrange = new javax.swing.JLabel();
        lTremble = new javax.swing.JLabel();
        lBalance = new javax.swing.JLabel();
        lVolume = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        slBass = new javax.swing.JSlider();
        slMidrange = new javax.swing.JSlider();
        slTremble = new javax.swing.JSlider();
        slBalance = new javax.swing.JSlider();
        slVolume = new javax.swing.JSlider();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        bStore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lBass.setText("Bass");
        getContentPane().add(lBass, new java.awt.GridBagConstraints());

        lMidrange.setText("Midrange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(lMidrange, gridBagConstraints);

        lTremble.setText("Tremble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(lTremble, gridBagConstraints);

        lBalance.setText("Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(lBalance, gridBagConstraints);

        lVolume.setText("Volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(lVolume, gridBagConstraints);

        jLabel6.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(jLabel6, gridBagConstraints);

        slBass.setMajorTickSpacing(2);
        slBass.setMaximum(10);
        slBass.setMinimum(-10);
        slBass.setMinorTickSpacing(1);
        slBass.setPaintLabels(true);
        slBass.setPaintTicks(true);
        slBass.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(slBass, gridBagConstraints);

        slMidrange.setMajorTickSpacing(2);
        slMidrange.setMaximum(10);
        slMidrange.setMinimum(-10);
        slMidrange.setMinorTickSpacing(1);
        slMidrange.setPaintLabels(true);
        slMidrange.setPaintTicks(true);
        slMidrange.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(slMidrange, gridBagConstraints);

        slTremble.setMajorTickSpacing(2);
        slTremble.setMaximum(10);
        slTremble.setMinimum(-10);
        slTremble.setMinorTickSpacing(1);
        slTremble.setPaintLabels(true);
        slTremble.setPaintTicks(true);
        slTremble.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(slTremble, gridBagConstraints);

        table.put(new Integer(0), new JLabel("Center"));
        table.put(new Integer(-5), new JLabel("L"));
        table.put(new Integer(5), new JLabel("R"));
        slBalance.setLabelTable(table);
        slBalance.setMajorTickSpacing(2);
        slBalance.setMaximum(5);
        slBalance.setMinimum(-5);
        slBalance.setMinorTickSpacing(1);
        slBalance.setPaintLabels(true);
        slBalance.setPaintTicks(true);
        slBalance.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(slBalance, gridBagConstraints);

        slVolume.setMajorTickSpacing(1);
        slVolume.setMaximum(10);
        slVolume.setPaintLabels(true);
        slVolume.setPaintTicks(true);
        slVolume.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(slVolume, gridBagConstraints);

        jRadioButton1.setText("jRadioButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("jRadioButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setText("jRadioButton3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton3, gridBagConstraints);

        bStore.setText("Store");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(bStore, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bStore;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lBalance;
    private javax.swing.JLabel lBass;
    private javax.swing.JLabel lMidrange;
    private javax.swing.JLabel lTremble;
    private javax.swing.JLabel lVolume;
    private javax.swing.JSlider slBalance;
    private javax.swing.JSlider slBass;
    private javax.swing.JSlider slMidrange;
    private javax.swing.JSlider slTremble;
    private javax.swing.JSlider slVolume;
    // End of variables declaration//GEN-END:variables
}
