
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dmarina
 */
public class Air_Teith extends javax.swing.JFrame {

    /**
     * Creates new form Air_Teith
     */
    public Air_Teith() {
        initComponents();
        FromDateChooser.setDateFormatString("dd/MM/yyyy");
        ToDateChooser.setDateFormatString("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SaveFileChooser = new javax.swing.JFileChooser();
        OpenFileChooser = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlaceFrom = new javax.swing.JList(FromPlace);
        PlaceTo = new javax.swing.JComboBox(ΤοPlace);
        OneWay = new javax.swing.JRadioButton();
        Return = new javax.swing.JRadioButton();
        ToDateChooser = new com.toedter.calendar.JDateChooser();
        FromDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FlightBooking = new javax.swing.JButton();
        FlightSearching = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air TeiTH");

        PlaceFrom.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jScrollPane1.setViewportView(PlaceFrom);

        PlaceTo.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        PlaceTo.setMaximumRowCount(10);

        buttonGroup1.add(OneWay);
        OneWay.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        OneWay.setText("Απλή Μετάβαση");
        OneWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OneWayItemStateChanged(evt);
            }
        });

        buttonGroup1.add(Return);
        Return.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        Return.setSelected(true);
        Return.setText("Με επιστροφή");
        Return.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReturnItemStateChanged(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 26)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        FlightBooking.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        FlightBooking.setText("Κράτηση");
        FlightBooking.setEnabled(false);
        FlightBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightBookingActionPerformed(evt);
            }
        });

        FlightSearching.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        FlightSearching.setText("Αναζήτηση");
        FlightSearching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightSearchingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setText("Επιλέξτε την Αφετηρία");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setText("Επιλέξτε τον Προορισμό");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel3.setText("Ημερομηνία Αναχώρισης");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Ημερομηνία Επιστροφής");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel6.setText("Στοιχεία Αναζήτησης");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlaceTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ToDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(FromDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FlightSearching, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OneWay)
                            .addComponent(Return))
                        .addContainerGap(75, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(FlightBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(FromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlaceTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OneWay)
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Return)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(ToDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19)
                .addComponent(FlightSearching)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FlightBooking)
                        .addGap(141, 141, 141)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightBookingActionPerformed
        // TODO add your handling code here:
        showReservation();
        saveFile();
    }//GEN-LAST:event_FlightBookingActionPerformed

    private void FlightSearchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightSearchingActionPerformed
        // TODO add your handling code here:
     flights(PlaceFrom.getSelectedValue(), String.valueOf(PlaceTo.getSelectedItem()), Tprice);
          
        
        FlightBooking.setEnabled(avaliable);
        for (int i=0; i<=11 ; i++ ) {
            if (Return.isSelected()){
                if (flightStatus[i].flightFrom.equals(PlaceFrom.getSelectedValue()) && flightStatus[i].flightTo.equals(String.valueOf(PlaceTo.getSelectedItem()) )){
                    dates();
                    jLabel5.setText("<html> Αφετηρία: " + flightStatus[i].flightFrom+
                                    "<br> Προορισμός: " + flightStatus[i].flightTo+
                                    "<br> Αναχώριση: " + from+
                                    "<br> Επιστροφή: " + to+ 
                                    "<br> Η τιμη είναι: " + flightStatus[i].flightPrice*2);
                    avaliable = true;
                    FlightBooking.setEnabled(avaliable);
                    ivalue=i;
                    break;}
               else {
                    myinfomessage("Η πτήση δεν είναι διαθέσιμη");
                    break;
                }
            }
            else { 
                avaliable=false;
                if (flightStatus[i].flightFrom.equals(PlaceFrom.getSelectedValue())){
                        dates();

                        jLabel5.setText("<html> Αφετηρία: " + flightStatus[i].flightFrom+
                                        "<br> Προορισμός: " + flightStatus[i].flightTo+
                                        "<br> Αναχώριση: " + from+
                                        "<br> Η τιμη είναι: " +flightStatus[i].flightPrice);
                        avaliable = true;
                        FlightBooking.setEnabled(avaliable);
                        ivalue=i;
                        break;}
               else {
                    myinfomessage("Η πτήση δεν είναι διαθέσιμη");
                    break;
                }
            }
        }
    }//GEN-LAST:event_FlightSearchingActionPerformed

    private void OneWayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OneWayItemStateChanged
        FlightBooking.setEnabled(false); 
        ToDateChooser.setEnabled(false);
    }//GEN-LAST:event_OneWayItemStateChanged

    private void ReturnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReturnItemStateChanged
        FlightBooking.setEnabled(true); 
        ToDateChooser.setEnabled(true);
    }//GEN-LAST:event_ReturnItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Air_Teith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Air_Teith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Air_Teith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Air_Teith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Air_Teith().setVisible(true);
            }
        });
    }
    
void flights(String fr, String to,  int price){
    flightStatus[0] = new Flights("Αθήνα", "Θεσσαλονίκη", 30);
    flightStatus[1] = new Flights("Αθήνα", "Ηράκλειο", 40);
    flightStatus[2] = new Flights("Αθήνα", "Κέρκυρα", 35);
    flightStatus[3] = new Flights("Αθήνα", "Ρόδος", 43);
    flightStatus[4] = new Flights("Θεσσαλονίκη", "Αθήνα", 28);
    flightStatus[5] = new Flights("Θεσσαλονίκη", "Μύκονος",  47);
    flightStatus[6] = new Flights("Θεσσαλονίκη", "Χανιά",  51);
    flightStatus[7] = new Flights("Θεσσαλονίκη", "Λεμεσός",  60);
    flightStatus[8] = new Flights("Θεσσαλονίκη", "Κεφαλονιά", 46);
    flightStatus[9] = new Flights("Θεσσαλονίκη", "Σαντορίνη",42);
    flightStatus[10] = new Flights("Θεσσαλονίκη", "Ρόδος",54);
    flightStatus[11] = new Flights("Θεσσαλονίκη", "Κέρκυρα",37);
      
}
   

void showReservation(){
    dates();
    if (Return.isSelected()){
        jTextArea1.setText(" Αφετηρία: " + flightStatus[ivalue].flightFrom + '\n' +
                    " Προορισμός: " + flightStatus[ivalue].flightTo+'\n' +
                    " Αναχώριση: " + from +'\n' +
                    " Επιστροφή: " + to + '\n'+
                    " Η τιμη είναι: " + flightStatus[ivalue].flightPrice*2 + '\n' + 
                    " " );
        }
    else {
        jTextArea1.setText(" Αφετηρία: " + flightStatus[ivalue].flightFrom + '\n' +
                    " Προορισμός: " + flightStatus[ivalue].flightTo+'\n' +
                    " Αναχώριση: " + from +'\n' +
                    " Η τιμη είναι: " + flightStatus[ivalue].flightPrice + '\n' + 
                    " " );
    }
} 

void saveFile(){
    FileWriter fw;
        int returnVal = SaveFileChooser.showSaveDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            filename = SaveFileChooser.getSelectedFile().getPath();
            if(filename.equals(""))
                myerrormessage("ERROR");
            else {
                try {
                    fw = new FileWriter(filename);
                    jTextArea1.write(fw);
                    fw.close();
                    myinfomessage("OK");
                   
                } catch(IOException exc) {
                    myinfomessage(exc.getMessage());
                }   
            }
         } else if (returnVal == JFileChooser.CANCEL_OPTION) {
             myinfomessage("You pressed cancel");
         }    
}
    
    void myerrormessage (String message) {
        JOptionPane.showMessageDialog(null, 
                                     message, 
                                     "Προσοχή Λάθος", 
                                     JOptionPane.ERROR_MESSAGE);
    }
    
    void myinfomessage (String message) {
        JOptionPane.showMessageDialog(null, 
                                     message, 
                                     "Ενημέρωση", 
                                     JOptionPane.INFORMATION_MESSAGE);
    }
    
    void dates(){
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
     from = sdf.format(FromDateChooser.getDate());
     to = sdf.format(ToDateChooser.getDate());
    }
    boolean avaliable=false;
    String filename = "";
    int returnval = 0;
    Flights flightStatus[] = new Flights[12];
    int ivalue;
    int Tprice;
    String FromPlace [] = {"Αθήνα", "Θεσσαλονίκη", "Ηράκλειο", "Κέρκυρα", "Ρόδος","Μύκονος", "Χανιά", "Λεμεσός","Κεφαλονιά", "Σαντορίνη"};
    String ΤοPlace [] = {"Αθήνα", "Θεσσαλονίκη", "Ηράκλειο", "Κέρκυρα", "Ρόδος","Μύκονος", "Χανιά", "Λεμεσός","Κεφαλονιά", "Σαντορίνη"};
    String from;
    String to;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlightBooking;
    private javax.swing.JButton FlightSearching;
    private com.toedter.calendar.JDateChooser FromDateChooser;
    private javax.swing.JRadioButton OneWay;
    private javax.swing.JFileChooser OpenFileChooser;
    private javax.swing.JList<String> PlaceFrom;
    private javax.swing.JComboBox<String> PlaceTo;
    private javax.swing.JRadioButton Return;
    private javax.swing.JFileChooser SaveFileChooser;
    private com.toedter.calendar.JDateChooser ToDateChooser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
