/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gsak3
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AFM = new javax.swing.JTextField();
        eponymo = new javax.swing.JTextField();
        onoma = new javax.swing.JTextField();
        dieuthinsi = new javax.swing.JTextField();
        arithmosPaidiwn = new javax.swing.JTextField();
        montelo = new javax.swing.JComboBox<>();
        posoAgoras = new javax.swing.JTextField();
        extraYN = new java.awt.Checkbox();
        posoExtra = new javax.swing.JTextField();
        posoAposirsis = new javax.swing.JTextField();
        ekthesiako = new java.awt.Checkbox();
        gratsounies = new java.awt.Checkbox();
        prosfora = new java.awt.Checkbox();
        PrintFrame = new javax.swing.JFrame();
        showText = new javax.swing.JLabel();
        showPrice = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Print = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();

        jLabel1.setText("Αριθμός Φορολογιακού Μητρώου");

        jLabel2.setText("Επώνυμο");

        jLabel3.setText("Όνομα");

        jLabel4.setText("Διεύθυνση");

        jLabel5.setText("Αριθμός Παιδιών");

        jLabel6.setText("Μοντέλο Αυτοκινήτου");

        jLabel7.setText("Ποσό Αγοράς");

        jLabel8.setText("Extra Εξαρτήματα");

        jLabel9.setText("Ποσό Αγοράς Έξτρα Εξαρτημάτων");

        jLabel10.setText("Ποσό Απόσυρσης ");

        jLabel11.setText("Εκθεσιακό Κομμάτι");

        jLabel12.setText("Γρατσουνιές");

        jLabel13.setText("Προσφορά");

        AFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFMActionPerformed(evt);
            }
        });

        eponymo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eponymoActionPerformed(evt);
            }
        });

        onoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onomaActionPerformed(evt);
            }
        });

        dieuthinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieuthinsiActionPerformed(evt);
            }
        });

        arithmosPaidiwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arithmosPaidiwnActionPerformed(evt);
            }
        });

        montelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota 2011", "BMW 2015" }));
        montelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monteloItemStateChanged(evt);
            }
        });
        montelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monteloActionPerformed(evt);
            }
        });

        posoAgoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posoAgorasActionPerformed(evt);
            }
        });

        extraYN.setLabel("");
        extraYN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                extraYNItemStateChanged(evt);
            }
        });

        posoExtra.setEnabled(false);
        posoExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posoExtraActionPerformed(evt);
            }
        });

        posoAposirsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posoAposirsisActionPerformed(evt);
            }
        });

        ekthesiako.setLabel("");
        ekthesiako.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ekthesiakoItemStateChanged(evt);
            }
        });

        gratsounies.setLabel("");
        gratsounies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gratsouniesItemStateChanged(evt);
            }
        });

        prosfora.setLabel("");
        prosfora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                prosforaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout NewFrameLayout = new javax.swing.GroupLayout(NewFrame.getContentPane());
        NewFrame.getContentPane().setLayout(NewFrameLayout);
        NewFrameLayout.setHorizontalGroup(
            NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewFrameLayout.createSequentialGroup()
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arithmosPaidiwn)
                            .addComponent(eponymo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AFM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dieuthinsi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(montelo, 0, 94, Short.MAX_VALUE)
                            .addComponent(onoma)
                            .addComponent(extraYN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(posoAgoras, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(NewFrameLayout.createSequentialGroup()
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(posoExtra)
                            .addComponent(posoAposirsis)
                            .addComponent(ekthesiako, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gratsounies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prosfora, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap(594, Short.MAX_VALUE))
        );
        NewFrameLayout.setVerticalGroup(
            NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewFrameLayout.createSequentialGroup()
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(AFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eponymo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(onoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dieuthinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(arithmosPaidiwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(montelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(posoAgoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(extraYN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(posoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(posoAposirsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(ekthesiako, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(gratsounies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(prosfora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrintFrameLayout = new javax.swing.GroupLayout(PrintFrame.getContentPane());
        PrintFrame.getContentPane().setLayout(PrintFrameLayout);
        PrintFrameLayout.setHorizontalGroup(
            PrintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PrintFrameLayout.createSequentialGroup()
                        .addComponent(showPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        PrintFrameLayout.setVerticalGroup(
            PrintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(showText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(showPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        File.setText("File");

        New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        File.add(New);

        Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        File.add(Print);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        About.setText("About");
        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        NewFrame.setVisible(true);
        NewFrame.setSize(750, 700);
    }//GEN-LAST:event_NewActionPerformed

    private void extraYNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_extraYNItemStateChanged
        // TODO add your handling code here:
        if(posoExtra.isEnabled())
        {
            posoExtra.setText("") ;
            posoExtra.setEnabled(false) ;
            extraYNS = false ;
            posoAgorasExtraS = 0 ;
        }
        else
        {
            extraYNS = true ; 
            posoExtra.setEnabled(true) ;
        }
    }//GEN-LAST:event_extraYNItemStateChanged

    private void posoAposirsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posoAposirsisActionPerformed
        // TODO add your handling code here:
        posoAposirsisS = Double.parseDouble(posoAposirsis.getText()) ;
    }//GEN-LAST:event_posoAposirsisActionPerformed

    private void AFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFMActionPerformed
        // TODO add your handling code here:
        afmS = AFM.getText() ;
    }//GEN-LAST:event_AFMActionPerformed

    private void eponymoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eponymoActionPerformed
        // TODO add your handling code here:
        eponymoS = eponymo.getText() ;
    }//GEN-LAST:event_eponymoActionPerformed

    private void onomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onomaActionPerformed
        // TODO add your handling code here:
        onomaS = onoma.getText() ;
    }//GEN-LAST:event_onomaActionPerformed

    private void dieuthinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieuthinsiActionPerformed
        // TODO add your handling code here:
        dieythinsiS = dieuthinsi.getText() ;
    }//GEN-LAST:event_dieuthinsiActionPerformed

    private void arithmosPaidiwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arithmosPaidiwnActionPerformed
        // TODO add your handling code here:
        arithmosPaidiwnS = Integer.parseInt(arithmosPaidiwn.getText()) ;
    }//GEN-LAST:event_arithmosPaidiwnActionPerformed

    private void monteloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monteloItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_monteloItemStateChanged

    private void monteloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monteloActionPerformed
        // TODO add your handling code here:
        if(findTheModel)
        {
            findTheModel = false ;
            modeloS = "BMW 2015" ;
        }
        else
        {
            findTheModel = true ;
            modeloS = "Toyota 2011" ;
        }
    }//GEN-LAST:event_monteloActionPerformed

    private void posoAgorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posoAgorasActionPerformed
        // TODO add your handling code here:
        posoAgorasS = Double.parseDouble(posoAgoras.getText()) ;
    }//GEN-LAST:event_posoAgorasActionPerformed

    private void posoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posoExtraActionPerformed
        // TODO add your handling code here:
        posoAgorasExtraS = Double.parseDouble(posoExtra.getText()) ;
    }//GEN-LAST:event_posoExtraActionPerformed

    private void ekthesiakoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ekthesiakoItemStateChanged
        // TODO add your handling code here:
        if(ekthesiakoS == true)
        {
            ekthesiakoS = false ;
        }
        else
        {
            ekthesiakoS = true ;
        }
    }//GEN-LAST:event_ekthesiakoItemStateChanged

    private void gratsouniesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gratsouniesItemStateChanged
        // TODO add your handling code here:
        if(gratsouniesS == false)
        {
            gratsouniesS = true ;
        }
        else
        {
            gratsouniesS = false ;
        }
    }//GEN-LAST:event_gratsouniesItemStateChanged

    private void prosforaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_prosforaItemStateChanged
        // TODO add your handling code here:
        if(prosforaS == false)
        {
            prosforaS = true ;
        }
        else
        {
            prosforaS = false ; 
        }
    }//GEN-LAST:event_prosforaItemStateChanged

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        PrintFrame.setVisible(true) ;
        PrintFrame.setSize(350, 350);
        posoAgorasS = Double.parseDouble(posoAgoras.getText()) ;
        posoAgorasExtraS = Double.parseDouble(posoExtra.getText()) ;
        telikoPoso = posoAgorasS + posoAgorasExtraS ;
        if(arithmosPaidiwnS >= 3)
        {
            telikoPosoText += " | polyteknoi : NAI" ;
            telikoPoso = telikoPoso * 90/100 ;
        }
        if(ekthesiakoS)
        {
            telikoPosoText += " | ekthesiako : NAI" ;
            telikoPoso = telikoPoso * 95/100 ; 
        }
        if(gratsouniesS)
        {
            telikoPosoText += " | gratsounies : NAI" ;
            telikoPoso = telikoPoso * 95/100 ; 
        }
        if(prosforaS)
        {
            telikoPosoText += " | prosfora : NAI" ;
            telikoPoso = telikoPoso * 85/100 ; 
        }
        showText.setText(telikoPosoText) ;
        showPrice.setText(String.valueOf(telikoPoso)) ;
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFM;
    private javax.swing.JMenu About;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem New;
    private javax.swing.JFrame NewFrame;
    private javax.swing.JMenuItem Print;
    private javax.swing.JFrame PrintFrame;
    private javax.swing.JTextField arithmosPaidiwn;
    private javax.swing.JTextField dieuthinsi;
    private java.awt.Checkbox ekthesiako;
    private javax.swing.JTextField eponymo;
    private java.awt.Checkbox extraYN;
    private java.awt.Checkbox gratsounies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> montelo;
    private javax.swing.JTextField onoma;
    private javax.swing.JTextField posoAgoras;
    private javax.swing.JTextField posoAposirsis;
    private javax.swing.JTextField posoExtra;
    private java.awt.Checkbox prosfora;
    private javax.swing.JLabel showPrice;
    private javax.swing.JLabel showText;
    // End of variables declaration//GEN-END:variables
    private boolean findTheModel = true ; 
    private String afmS ;
    private String eponymoS ; 
    private String onomaS ; 
    private String dieythinsiS ;
    private int arithmosPaidiwnS ;
    private String modeloS ;
    private double posoAgorasS = 0;
    private boolean extraYNS = false ; 
    private double posoAgorasExtraS = 0 ; 
    private double posoAposirsisS ; 
    private boolean ekthesiakoS = false ;
    private boolean gratsouniesS = false ;  
    private boolean prosforaS = false ;
    private double telikoPoso = 0 ; 
    private String telikoPosoText = "" ; 
}
